// `download` returns a stream, never a buffer — held to an actual gigabyte
// (#167).
//
// The done-when is not "returns something stream-shaped", it is "a gigabyte
// file must not be materialised in memory", and those are different claims. A
// method that buffers the response and hands back a `ReadableStream` over the
// result satisfies the first and fails the second, and no type signature can
// tell them apart. So this suite does both halves: a structural check that the
// success path never calls a buffering method on the response, and a gigabyte
// actually crossing a socket while the process's memory is watched.
//
// The bytes are generated, not read off a disk. A gigabyte fixture file would
// make this suite slow, leave a gigabyte behind when it failed part-way, and
// prove nothing extra — what is under test is this package's reading of a
// response body, and the socket does not know where the Core got the bytes.
import { afterEach, describe, expect, it } from "vitest";
import * as http from "node:http";
import { CoreClient } from "../core-client";
import type { CoreFilesFetch } from "../core-files-http";
import { startCoreRig, type CoreRig } from "./fake-core-link";

const GIGABYTE = 1024 * 1024 * 1024;
const CHUNK = 64 * 1024;
/**
 * The headroom a streaming read is allowed. Generous — undici's own buffers,
 * V8's heap and whatever the runner was already holding all land inside it —
 * and still two orders of magnitude below the failure it exists to catch,
 * which is a gigabyte arriving all at once.
 */
const HEADROOM = 192 * 1024 * 1024;

let server: http.Server | null = null;
let client: CoreClient | null = null;
let coreRig: CoreRig | null = null;

afterEach(async () => {
  client?.close();
  client = null;
  coreRig?.close();
  coreRig = null;
  const running = server;
  server = null;
  if (running) {
    running.closeAllConnections();
    await new Promise<void>((resolve) => running.close(() => resolve()));
  }
});

/** A Core-shaped server that streams `total` generated bytes and never holds them. */
async function serveBytes(total: number): Promise<{ host: string; port: number }> {
  const chunk = Buffer.alloc(CHUNK, 0x61);
  server = http.createServer((_req, res) => {
    res.writeHead(200, {
      "content-type": "application/octet-stream",
      "content-length": String(total),
      "x-actana-transfer-kind": "file",
      "x-actana-file-size": String(total),
      "x-actana-file-mode": "420",
    });
    let sent = 0;
    const pump = (): void => {
      while (sent < total) {
        const size = Math.min(CHUNK, total - sent);
        const slice = size === CHUNK ? chunk : chunk.subarray(0, size);
        sent += size;
        if (!res.write(slice)) {
          res.once("drain", pump);
          return;
        }
      }
      res.end();
    };
    pump();
  });
  await new Promise<void>((resolve) => server!.listen(0, "127.0.0.1", resolve));
  const address = server.address();
  if (!address || typeof address === "string") throw new Error("no port");
  return { host: "127.0.0.1", port: address.port };
}

async function clientFor(where: { host: string; port: number }): Promise<CoreClient> {
  coreRig = startCoreRig({ announceFiles: true });
  client = new CoreClient({
    url: `ws://${where.host}:${where.port}`,
    createSocket: coreRig.dialer().createSocket,
  });
  await client.connect();
  return client;
}

describe("download", () => {
  it(
    "streams a gigabyte without materialising it",
    { timeout: 120_000 },
    async () => {
      const core = await clientFor(await serveBytes(GIGABYTE));

      const file = await core.project("proj_1").files.download({ path: "huge.bin" });
      expect(file.size).toBe(GIGABYTE);

      const before = process.memoryUsage();
      let received = 0;
      let peakArrayBuffers = 0;
      let peakRss = 0;
      const reader = file.stream.getReader();
      for (;;) {
        const next = await reader.read();
        if (next.done) break;
        received += next.value.byteLength;
        // Sampled rather than measured every chunk: 16384 `memoryUsage()` calls
        // would dominate the runtime of the thing being measured.
        if (received % (64 * CHUNK) === 0) {
          const now = process.memoryUsage();
          peakArrayBuffers = Math.max(peakArrayBuffers, now.arrayBuffers - before.arrayBuffers);
          peakRss = Math.max(peakRss, now.rss - before.rss);
        }
      }

      expect(received).toBe(GIGABYTE);
      // `arrayBuffers` is where a buffered body would live — every chunk undici
      // hands over is backed by one, and a `res.arrayBuffer()` would be a single
      // allocation the size of the file. This is the discriminating measurement;
      // RSS is the sanity check beside it.
      expect(peakArrayBuffers).toBeLessThan(HEADROOM);
      expect(peakRss).toBeLessThan(HEADROOM);
    },
  );

  it("never calls a buffering method on the response", async () => {
    // The structural half. A future edit that reached for `res.arrayBuffer()`
    // to, say, compute a digest would pass every other test in this directory
    // and quietly reintroduce the gigabyte — this is what stops it, and it
    // names the methods so the failure says which one was called.
    const forbidden: string[] = [];
    const send: CoreFilesFetch = () => {
      const response = new Response("hello", {
        status: 200,
        headers: { "x-actana-transfer-kind": "file", "content-length": "5" },
      });
      for (const method of ["arrayBuffer", "text", "blob", "bytes", "json", "formData"] as const) {
        Object.defineProperty(response, method, {
          value: () => {
            forbidden.push(method);
            throw new Error(`download must not call ${method}()`);
          },
        });
      }
      return Promise.resolve(response);
    };
    coreRig = startCoreRig({ announceFiles: true });
    client = new CoreClient({
      url: "ws://127.0.0.1:1",
      createSocket: coreRig.dialer().createSocket,
      filesFetch: send,
    });
    await client.connect();

    const file = await client.project("proj_1").files.download({ path: "a.txt" });
    const reader = file.stream.getReader();
    await reader.read();
    await reader.cancel();

    expect(forbidden).toEqual([]);
  });

  it("hands back the body itself, so nothing has been read before the caller looks", async () => {
    // `disturbed` is the stream's own record of whether anything has read from
    // it. False here means `download` resolved without touching the body — the
    // caller gets all of it, including the first byte.
    const body = new ReadableStream<Uint8Array>({
      pull(controller) {
        controller.enqueue(new TextEncoder().encode("x"));
        controller.close();
      },
    });
    coreRig = startCoreRig({ announceFiles: true });
    client = new CoreClient({
      url: "ws://127.0.0.1:1",
      createSocket: coreRig.dialer().createSocket,
      filesFetch: () => Promise.resolve(new Response(body, { status: 200 })),
    });
    await client.connect();

    const file = await client.project("proj_1").files.download({ path: "a.txt" });

    expect(file.stream.locked).toBe(false);
    expect(await new Response(file.stream).text()).toBe("x");
  });
});
