// GENERATED by scripts/gen-skill-payload.mjs — do not edit.
//
// The source is `.agents/skills/actana-sessions/SKILL.md`, and the drift test beside this file fails
// when the two disagree. Edit the markdown, re-run the generator, commit both.
// ADR 0031 D8 is why this is embedded rather than read off disk.

/** The skill's directory name — its address in a harness's skills root. */
export const ORCHESTRATION_SKILL_NAME = "actana-sessions";

/**
 * The in-band marker that makes a copy ours (ADR 0031 D1).
 *
 * The authorisation to overwrite, and the operator's escape hatch: delete this
 * line from a copy and the installer never touches that file again.
 */
export const ORCHESTRATION_SKILL_MARKER = "x-actana-managed: true";

/** The authored `SKILL.md`, byte for byte. */
export const ORCHESTRATION_SKILL_MD = `---
name: actana-sessions
description: Drive Actana Control Cores and Sessions with the \`actana\` CLI — register and select a Core, see which Harnesses it can run, start Sessions with a prompt, wait for them to settle, read what they produced, send follow-up input, and stop them. Use when asked to run work in one or more Sessions, to provision several Sessions at once ("give me three sessions, each on a different thing"), to check on or collect results from Sessions already running, or whenever a task would be done by another agent on a Core rather than here.
x-actana-managed: true
---

# Driving Cores and Sessions with \`actana\`

\`actana\` is a client. A **Core** is a machine running the Actana Control daemon;
a **Session** is one Harness process — a vendor's coding agent — running on that
Core inside a **Project**. Sessions belong to the Core, not to this command: a
Session keeps running after \`actana\` exits, and any later \`actana\` invocation
can list it, read it, write to it or stop it.

If \`actana\` is not on this machine, or reports no Core, say so and stop. Do not
install anything and do not guess at a Core's address.

## Orientation, in the order that answers the questions

\`\`\`bash
actana core ls                 # Cores this machine can reach; * marks the selected one
actana core use <name>         # select one for subsequent commands
actana harness ls --json       # what the selected Core can actually run, right now
actana project ls --json       # the Projects on that Core; a Session needs one
actana session ls --json       # Sessions already running there
\`\`\`

\`--core <name>\` overrides the selection for a single command. Every list verb
takes \`--json\`, and under \`--json\` only the JSON document reaches stdout —
diagnostics go to stderr — so parsing is safe.

**Pick the Harness from what \`harness ls\` reports, every time.** It lists each
Harness with a \`status\` of \`available\` or \`missing\`; only \`available\` can run.
There is no default and no preference order here on purpose — operators have
their own, this skill has none, and a Harness that was available yesterday may
be missing today. Ask the operator if the choice matters to them and nothing in
the request settles it.

## Starting one Session

\`\`\`bash
actana session start <project> "<prompt>"            # prints the session id, exits
actana session start <project> "<prompt>" --json     # the same as an object
actana session start <project> - < brief.md          # a prompt of \`-\` is read from stdin
\`\`\`

Useful flags: \`--harness <id>\` (one of the ids \`harness ls\` printed),
\`--title <text>\` (what it is called in a listing), \`--cwd <path>\` (a directory
**on the Core**, inside the Project), \`--dangerously-skip-permissions\` (run the
Harness without permission prompts — only when the operator has asked for
unattended work).

\`start\` returns as soon as the Core has the Session running. The prompt is
delivered by the Core, which watches the Harness boot and types when it is
ready; add no delays, no leading newline and no "press enter" of your own.

## Waiting, and reading the result

\`\`\`bash
actana session start <project> "<prompt>" --wait --json --wait-timeout 900
\`\`\`

**\`--wait --json\` is the reliable way to collect a result, and the reason is
mechanical.** A Session's transcript lives in a replay ring that belongs to the
Harness's terminal, so a Harness that has exited has taken its output with it
and a later \`actana session logs\` has nothing left to print. The object
\`--wait --json\` prints carries a \`screen\` field holding the transcript as it
settled, in the same document as the status — so the result is in hand before
the process it came from can disappear.

The object also carries \`taskId\` (the Session's id — this is what every other
verb takes), \`harness\`, \`project\`, \`status\`, \`exited\`, and \`reportsTurnStart\`.
\`--wait-timeout <seconds>\` bounds the wait; without it the wait has no deadline
of its own. A timeout is this side giving up, not a verdict about the Session:
the Session is still running on the Core and can still be listed, read and
stopped.

While a Session is alive you can also look at it directly:

\`\`\`bash
actana session logs <id>          # the transcript, rendered, while the harness is running
actana session send <id> "text"   # write into it; --enter follows with a carriage return
actana session kill <id>          # stop the harness running for it
\`\`\`

\`actana events tail --json\` follows the Core's event log as NDJSON if you want
to watch state change rather than poll — \`session:finished\` is the Core's own
signal that a Session reached a terminal state.

## Asking a Session for a machine-readable report

A screen is a transcript, not a result. When you need a Session to hand back
something you can parse, tell it in the prompt to end with its report wrapped in
a sentinel pair, and take the report out of the settled screen.

The sentinel is \`<%ACT_REPORT%>\` … \`<%/ACT_REPORT%>\`, and the four rules matter
as much as the token:

1. **The token is deliberately unusual.** Ordinary prose, code samples and test
   fixtures never contain \`<%ACT_REPORT%>\`, so a match is a report and not a
   coincidence.
2. **It is a pair, not a single marker.** A lone marker is unrecoverable the
   moment the Harness prints anything after its report — there is no way to
   tell where the report ended.
3. **The last complete pair wins.** A conversation runs many turns and may emit
   the sentinel more than once; the pair nearest the end is the final state.
   An incomplete trailing opener is not a report.
4. **Match with whitespace stripped.** What you are reading is a *rendered
   screen*, produced by a terminal emulator with a fixed width, so a tag that
   reaches the right margin is wrapped across two rows and a literal match
   fails. Strip whitespace — newlines included — from both the haystack and the
   tags before searching, and keep the original text for the extracted body.

Put the instruction in the prompt itself, in the Session's own words:

> When you are finished, print your result between \`<%ACT_REPORT%>\` and
> \`<%/ACT_REPORT%>\` on their own lines, and print nothing after the closing tag.

**Save the report before you stop the Session.** Killing a Session destroys the
replay ring the report is being read from — collect first, kill second, in that
order, always.

## Several Sessions at once

There is no batch verb. Provisioning N Sessions is N \`session start\` calls, and
that is deliberate: each one gets its own prompt, its own Harness and possibly
its own Project, and a Session that fails to start is one failure rather than a
failed batch.

The shape that works:

1. **Ask what is missing before starting anything.** How many Sessions, what
   each one is for, and which Project. If the operator said "three sessions,
   each focusing on three different things", the three things are theirs to
   name — do not invent a split and do not start work on a guess.
2. **Check \`harness ls\` once**, and use only \`available\` ids.
3. **Start each Session without \`--wait\`**, keeping the printed id and what you
   asked it for. Starting them all first is what makes them concurrent; a
   \`--wait\` in this loop makes them a queue.
4. **Give each one the sentinel instruction** in its prompt.
5. **Then collect.** Poll \`actana session ls --json\` for status, or follow
   \`actana events tail --json\` and watch for each id to finish. When a Session
   reaches a terminal status, read \`actana session logs <id>\` — while it is
   still alive — extract the last complete sentinel pair, and only then
   \`actana session kill <id>\`.
6. **Report per Session, by id**, including the ones that produced no parseable
   report. A Session that finished without a report is a fact, not a gap to
   fill in.

**How many to start is the operator's decision, not a rule.** Every Session is a
Harness process on somebody's machine costing somebody's tokens. Start the
number that was asked for; if no number was asked for, ask.

## When something is wrong

- **\`no Core registered\` / nothing from \`core ls\`** — the operator has not
  paired this machine with a Core. That is theirs to do (\`actana core add\`);
  say so rather than attempting it.
- **\`harness ls\` shows everything \`missing\`** — the Core has no coding agent
  installed. \`actana harness install <id>\` asks the Core to install one and
  waits for its verdict; it takes minutes and can legitimately fail.
- **A Session started but produced nothing** — check \`reportsTurnStart\` in the
  start object. When it is \`false\`, the Harness sends no turn-start signal and
  a Session can sit on \`ready\` through its whole first turn; wait on the
  Session's terminal status rather than on it looking busy.
- **\`session logs\` says the Session has no harness running** — the Harness has
  exited and its transcript is gone with it. Nothing recovers it. That is what
  \`--wait --json\` exists to prevent, next time.
- **A prompt seems not to have arrived** — do not retype it and do not send a
  bare carriage return. Delivery is the Core's job; a lost prompt is a bug to
  report with the Session's id, not a thing to work around from here.
`;
