// GENERATED by scripts/gen-skill-payload.mjs — do not edit.
//
// The sources are the folders under `.agents/skills/` named by
// `ORCHESTRATION_SKILL_NAMES` below, and
// `packages/shared/src/__tests__/orchestration-skill-fanout.test.ts` — the one
// drift test, in the one package that can read both copies — fails when the two
// disagree. Edit the authored files, re-run the generator, commit both.
// ADR 0031 D8 is why this is embedded rather than read off disk.

/**
 * The skill directory names — their addresses in a harness's skills root.
 *
 * Two of them since #303, and the order here is the order an installer reports
 * them in. A name is data: nothing downstream may branch on which one it is
 * holding, because the difference between the two roles is prose inside the
 * files and not behaviour in the writer (ADR 0035 D1).
 */
export const ORCHESTRATION_SKILL_NAMES: readonly string[] = ["actana-sessions", "actana-subagent"];

/**
 * The in-band marker that makes a copy ours (ADR 0031 D1).
 *
 * The authorisation to overwrite, and the operator's escape hatch: delete this
 * line from a copy and the installer never touches that file again. It is
 * matched as a substring of a file's first bytes rather than as a parsed key,
 * which is why the same marker works in `SKILL.md`'s frontmatter and in a
 * shell script's second line.
 */
export const ORCHESTRATION_SKILL_MARKER = "x-actana-managed: true";

/**
 * The authored skill folders, byte for byte: folder name to the folder's own
 * map of folder-relative path to contents.
 *
 * Inner keys are `/`-separated on every platform — the installer splits them
 * before joining. Every value carries the marker above; the generator refuses to
 * emit one that does not.
 *
 * Typed as plain records rather than left to infer their literal keys: a folder
 * name or a file name in here is data the installer is handed, never an
 * identifier anything branches on, and a type that made `"SKILL.md"` or
 * `"actana-subagent"` special would be the first step towards code that treats
 * it that way.
 */
export const ORCHESTRATION_SKILL_FILES: Readonly<
  Record<string, Readonly<Record<string, string>>>
> = {
  "actana-sessions": {
    "SKILL.md": `---
name: actana-sessions
description: Drive Actana Control Cores and Sessions with the \`actana\` CLI — register and select a Core, see which Harnesses it can run, start Sessions with a prompt, wait for them to settle, collect the report each one wrote, send follow-up input, and stop them. Use when asked to run work in one or more Sessions, to provision several Sessions at once ("give me three sessions, each on a different thing"), to check on or collect results from Sessions already running, or whenever a task would be done by another agent on a Core rather than here.
x-actana-managed: true
---

# Driving Cores and Sessions with \`actana\`

\`actana\` is a client. A **Core** is a machine running the Actana Control daemon;
a **Session** is one Harness process — a vendor's coding agent — running on that
Core inside a **Project**. Sessions belong to the Core, not to this command: a
Session keeps running after \`actana\` exits, and any later \`actana\` invocation
can list it, read it, write to it or stop it.

If \`actana\` is not on this machine, or reports no Core, say so and stop. Do not
install anything and do not guess at a Core's address.

**This skill is invoke-only, and the one installed beside it is not. The
asymmetry is deliberate — do not tidy it into symmetry.** This one sits
installed and does not volunteer: it is for a Session whose operator has asked
for work to be run in other Sessions. Its sibling, the sub-agent skill, is
**eager**: it triggers on a prompt telling a Session that it is acting as a
sub-agent of an orchestrating Session, and this skill is what teaches you to put
that declaration in every prompt you send. The two roles have opposite trigger
requirements — one is a thing an operator asks for, the other is a thing a
Session is *told it already is* by the prompt that woke it — and one
\`description\` field cannot hold both. That, and nothing about length or
tidiness, is why there are two files.

## Orientation, in the order that answers the questions

\`\`\`bash
actana core ls                 # Cores this machine can reach; * marks the selected one
actana core use <name>         # select one for subsequent commands
actana harness ls --json       # what the selected Core can actually run, right now
actana project ls --json       # the Projects on that Core; a Session needs one
actana session ls --json       # Sessions already running there
\`\`\`

\`--core <name>\` overrides the selection for a single command. Every list verb
takes \`--json\`, and under \`--json\` only the JSON document reaches stdout —
diagnostics go to stderr — so parsing is safe.

**On a machine that is itself a Core, that Core is already registered and
already selected.** Installing a Core wires it to the same machine's \`actana\`,
so \`core ls\` lists it and it is what every command below means unless \`--core\`
or \`core use\` says otherwise. Address it by default; do not ask the operator to
pair the machine you are already standing on.

**Pick the Harness from what \`harness ls\` reports, every time.** It lists each
Harness with a \`status\` of \`available\` or \`missing\`; only \`available\` can run.
There is no default and no preference order here on purpose — operators have
their own, this skill has none, and a Harness that was available yesterday may
be missing today. Ask the operator if the choice matters to them and nothing in
the request settles it.

## Starting one Session

\`\`\`bash
actana session start <project> "<prompt>"            # prints the session id, exits
actana session start <project> "<prompt>" --json     # the same as an object
actana session start <project> - < brief.md          # a prompt of \`-\` is read from stdin
\`\`\`

Useful flags: \`--harness <id>\` (one of the ids \`harness ls\` printed),
\`--title <text>\` (what it is called in a listing), \`--cwd <path>\` (a directory
**on the Core**, inside the Project), \`--dangerously-skip-permissions\` (run the
Harness without permission prompts — only when the operator has asked for
unattended work).

\`start\` returns as soon as the Core has the Session running. The prompt is
delivered by the Core, which watches the Harness boot and types when it is
ready; add no delays, no leading newline and no "press enter" of your own.

**Running is not the same fact as ready to be sent to.** The Harness is spawned
when \`start\` returns; it takes the prompt seconds later, once its composer is
up. A \`session send\` in between goes into a terminal that is not reading and is
discarded — along with the starting prompt queued behind it, so one impatient
line loses two messages. If the next thing you do is \`send\`, start with
\`--await-prompt\`:

\`\`\`bash
ID=$(actana session start <project> "<prompt>" --await-prompt)  # blocks until it landed
actana session send "$ID" "<follow-up>" --wait --json --wait-timeout 1800
\`\`\`

It blocks only until the Core reports the prompt delivered — seconds on a warm
Harness, not the length of a turn — prints the id as usual, and **exits non-zero
if the Core could not deliver it at all**, which is the one outcome a script
must not read as a started Session. \`--wait\` already includes it, so a start
that waits for the whole turn needs nothing extra. Without either, \`--json\`
answers \`promptDelivered: null\`: nobody adjudicated it.

**\`--harness\` is how one round spans several Harnesses.** Nothing else is
needed for it: each \`session start\` takes its own \`--harness\`, so a round of
lanes on different Harnesses is a round of ordinary starts. Pick every id out of
what \`harness ls --json\` reported as \`available\`, and never out of memory.

## Waiting, and reading the result

\`\`\`bash
actana session start <project> "<prompt>" --wait --json --wait-timeout 900
\`\`\`

**\`--wait --json\` blocks until that Session's first turn settles.** That is what
it is for, and it is worth having: it is one call that starts a Session and
returns when the turn it started has ended.

**What it is not is a way to collect a result.** The \`screen\` field on the
object it prints is a *rendered transcript* — a terminal emulator's picture of a
bounded replay ring. It is wrapped to a fixed width, the oldest lines are
dropped once the ring is full, a Harness that clears its scrollback discards all
of it with no error and no signal, and killing the Session destroys what is
left. A transcript is what a human reads over somebody's shoulder. **A result is
a file**, and the contract below is how you get one.

The object also carries \`taskId\` (the Session's id — this is what every other
verb takes), \`harness\`, \`project\`, \`status\`, \`exited\`, and \`reportsTurnStart\`.
\`--wait-timeout <seconds>\` bounds the wait; without it \`start --wait\` has no
deadline of its own (\`send --wait\` does — see the loop below). A timeout is this
side giving up, not a verdict about the Session: the Session is still running on
the Core and can still be listed, read and stopped.

While a Session is alive — which is what the \`live\` field on its
\`actana session ls --json\` row tells you, and the only thing that does — you can
also look at it directly:

\`\`\`bash
actana session logs <id>          # the transcript, rendered, while the harness is running
actana session send <id> "text"   # write into it; the carriage return that submits goes too
actana session wait <id>          # block until the Core reports it settled
actana session kill <id>          # stop the harness running for it
\`\`\`

\`actana events tail --json\` follows the Core's event log as NDJSON if you want
to watch state change rather than poll — \`session:finished\` is the Core's own
signal that a Session reached a terminal state. Both of these are for **watching
progress**. Neither is what tells you a report is ready; the last line of the
file is.

## The multi-turn loop

A Session is a conversation, not a single question. The whole loop:

\`\`\`bash
ID=$(actana session start <project> "<first prompt>")   # prints the id, exits
actana session wait "$ID" --json --wait-timeout 1800    # block until it settles
actana session send "$ID" "<follow-up>" --wait --json --wait-timeout 1800
actana session send "$ID" "<next>" --wait --json --wait-timeout 1800
\`\`\`

Every line carries the same budget on purpose: 1800 seconds is what \`await.sh\`
gives a round, and a loop whose steps disagree about how long a turn may take
gives up in the middle of one. Pass it explicitly rather than leaning on a
default — \`send --wait\` has one (1020 seconds) and the other two do not.

**\`actana session wait <id>\` blocks until the Core reports the Session settled**
— \`finished\`, \`needs-input\`, \`interrupted\`, \`terminated\` or \`disconnected\`,
because every one of those is a turn that ended. A Session that is already
settled answers at once, so a wait that starts after the turn ended is not a
wait that hangs.

**\`actana session send <id> "<text>" --wait\` waits for the turn that text
starts.** The Core stamps the delivery in its event log and the wait resolves on
the first settling status *after* that stamp, so it can never hand you the
status the Session was already parked at. With \`--json\` it prints the **same
object** \`start --wait --json\` prints — same keys, same \`screen\` — so one parser
reads all three verbs. Two of those keys are \`null\` on a Session you attached to
rather than started: \`command\` and \`reportsTurnStart\` are answers to a spawn.

Four things to know before you build on it:

1. **Sending into a turn that is already running resolves on *that* turn's
   end.** A keystroke into a busy Harness is not a new turn. If the Session was
   mid-turn when your text landed, the wait ends when the current turn ends —
   possibly before the Harness has read a character of what you sent. Wait for
   the Session to settle *first*, then send.
2. **A \`send\` presses Enter for you, and \`--no-enter\` is how you stop it.** The
   text goes first and the carriage return follows as its own separate write.
   \`--no-enter\` sends no return, so that send starts no turn — and it **cannot
   be combined with \`--wait\`**, which is refused as a usage error: a send that
   submits nothing has no turn to await. Type with \`--no-enter\`, then
   \`actana session wait\` once a turn is actually running. \`--enter\` is still
   accepted and does nothing on a send that carries text, so an older script
   that passes it keeps working; on a send with no text it still means a bare
   carriage return and nothing else.
3. **A timeout is this side giving up, not a status.** \`--wait-timeout
   <seconds>\` bounds the wait. \`session wait\` has no deadline unless you set
   one, because a turn takes as long as the work takes; **\`send --wait\` defaults
   to 1020 seconds**, because it is the one wait for a turn that has not started
   yet and a carriage return that lands on a dialog rather than a composer
   starts none at all. \`--wait-timeout 0\` waits with no deadline. On expiry you
   get a message saying the wait gave up and a non-zero exit — the Session is
   still running on the Core, and \`session logs\` and \`session kill\` still work.
   When no turn end was reported since your text went in, the message says so
   and names both readings: the text may have started no turn, or a turn may
   still be running on a Harness that reports nothing until it ends. The text
   was delivered either way — read the screen with \`session logs\` rather than
   sending it again.
4. **Do not answer that timeout with \`session wait\`.** It is uncursored: it
   answers from the status the Session is parked at, so on a turn that never
   started it returns **at once, with the status from before your text, and
   exits zero** — which reads as a completed turn and is not one. To carry on
   waiting, follow the log from the delivery instead:
   \`actana events tail --since <event id>\`, the id the timeout message names.

**Every turn of that loop gets its own report file**, and the turn number in the
filename is what keeps them apart. See below.

## Asking a Session for a report file

A Session hands work back by **writing a file on its own Core**. You read the
file back over the core link. Nothing in this path goes through a screen, a
renderer, a replay ring or a scrollback limit, and nothing in it can be
truncated by a Harness that decided to repaint.

The contract, in full. Every clause is load-bearing:

- **The path is \`.actana/reports/<id>-r<turn>.md\`, relative to the Session's own
  \`cwd\` on its own Core.** Dot-prefixed so it reads as machine state rather than
  as project content, and so it falls under the ignore habits operators already
  have for dot-directories. The Session's \`cwd\` is the anchor because it is the
  only directory a prompt can name in a sentence: a Session knows where it is
  standing and nothing else.
- **Everything that reads the file back is anchored at the Project root
  instead, and closing that gap is yours.** \`actana project cp\` takes
  \`<project>:<path>\` and resolves \`<path>\` against the **Project**, and so does
  every lane you hand \`await.sh\`. The two anchors are the same path only when
  the Session runs at the Project root. So:

  - **Start a lane you intend to collect with no \`--cwd\`, and the question does
    not arise.** A Session with no \`--cwd\` runs at the Project root, which is
    where the collectors are already anchored, and the prompt's path and the
    lane's path are one string.
  - **If a lane needs a \`--cwd\`, convert once, when you mint the name.**
    \`--cwd\` is a directory **on the Core**, so the lane's path is that
    directory *relative to the Project root*, followed by the path you put in
    the prompt. A Project \`api\` at \`/srv/work/api\`, started with
    \`--cwd /srv/work/api/apps/api\` and told \`.actana/reports/api-r1.md\`, is
    collected as the lane \`api:apps/api/.actana/reports/api-r1.md\`, and read
    with \`core exec --cwd /srv/work/api/apps/api -- tail -n 3 --\` and that same
    prompt path. Keep both forms beside the lane, and never derive one from the
    other twice.

  \`actana project ls --json\` prints each Project's \`path\`, which is the root
  both of those are relative to.

  Getting this wrong is silent. The sub-agent writes the file it was told to
  write, the collector looks somewhere else, and every lane in the round runs to
  its timeout reporting nothing — with no error anywhere, because nothing failed.
- **You mint the filename; the sub-agent never invents one.** You are the only
  party that knows every lane in the round, so you are the only party that can
  promise no two lanes collide. **Never reuse a name** — not across lanes, not
  across rounds, not across turns.
- **\`-r<turn>\` is the turn number and it is not decoration.** A round is often
  six turns in **one** Session. Without a per-turn name, turn 2 silently reads
  turn 1's file on any turn that failed to write one — a stale report
  indistinguishable from a fresh one, which is the worst failure available: a
  confident wrong answer.
- **The file's final line must be exactly \`ACT-REPORT-END\`.** That is the
  completeness proof and **the only thing that settles a Session**. Not a
  status, not an event, not a timeout — the last line of the file.
- **State the full relative path in the prompt, every turn.** Belt and braces:
  the skill at the other end teaches the convention, and your prompt restates
  the exact path. A skill is a document a model may have compressed; a prompt is
  in front of it.

Put it in the prompt in the Session's own words, and open with the declaration
that turns the sub-agent skill on at the other end:

> You are acting as a sub-agent of an orchestrating Session. When you are
> finished, write your complete report to \`.actana/reports/api-r1.md\` under the
> directory you are working in, creating the \`.actana/reports\` directory if it
> does not exist. The file's final line must be exactly \`ACT-REPORT-END\`.

**That first sentence is not a courtesy.** The sub-agent skill installed on that
Core is eager and triggers on exactly that declaration, so a prompt without it
wakes a Session that never learned the contract. Send it in **every** prompt you
send, follow-up turns included, with that turn's own path.

Say nothing else about the mechanism. What the Session should actually *do* is
yours to say, in the same prompt, in whatever detail the work needs — and any
skill you ask it to use travels there too.

## Collecting a report

\`actana core exec\` runs one command on the Core over the core link: no terminal,
no rendering, stdout as it was written.

\`\`\`bash
# --cwd here is the directory the Session is running in: the path you gave
# \`session start --cwd\`, or the Project's own \`path\` from \`project ls --json\`
# when you gave none. It is what the prompt's report path is relative to.
actana core exec --cwd <session-cwd> -- tail -n 3 -- .actana/reports/api-r1.md
actana core exec --core <name> --cwd <session-cwd> -- cat .actana/reports/api-r1.md
\`\`\`

The order below is the whole of it:

1. **Poll for the file.** A non-zero exit is almost always "not there yet",
   which is the ordinary state of a Session that is still working. One exit code
   is not: **125 means the link to the Core dropped mid-command** — the command
   kept running over there and this side has no answer. That is *ask again next
   tick*, never *no report*.
2. **Check the LAST line, not the file.** \`ACT-REPORT-END\` occurring anywhere
   else — quoted, inside a fenced block, in a diff — is not a finished report,
   and a search that matched it would settle a Session that has not finished.
   Read the tail and compare its last non-blank line.
3. **Save the content locally, first.** \`actana project cp <project>:<path>
   ./<local-path>\` copies it down. **\`<path>\` here is Project-relative** — this
   is the step where the anchor changes, so it is the lane's path and not the
   prompt's, and they differ by the Session's \`cwd\` whenever one was given. Give
   every lane its own local filename, because "three Sessions, each on a
   different thing" naturally gives every sub-agent the same basename inside its
   own Project.
4. **Only then, after roughly 20 seconds, delete the remote file** — with
   \`core exec\`, against the Session's own directory again, like steps 1 and 2:
   \`actana core exec --cwd <session-cwd> -- rm -f .actana/reports/api-r1.md\`. **The
   delay is not tidiness.** It exists so that a Session still finishing cannot
   have its file deleted out from under it and write it again, which would
   present as a second, partial report at a path you have already retired.

**Never delete before the local save.** The durable local artifact is the entire
point of reading a file rather than a screen, and deleting first reintroduces
exactly the failure this contract exists to end.

## \`await.sh\`, which does steps 1-3 of that for a whole round

This skill folder ships \`await.sh\` beside this file. It watches every lane in
**one** loop — a per-lane wait serialises a round, so a six-lane round runs at
the speed of its worst lane *summed* rather than its worst lane alone — checks
the last line rather than searching the file, treats a dropped link as "not
yet", and saves each report to local disk before it touches the Session.

**It does steps 1, 2 and 3. It never does step 4.** The script has no remote
delete and no ~20 second delay; once a lane's bytes are safely down it either
stops that Session under \`--kill\` or moves on. Retiring the remote file stays
yours, per lane, after the round. \`--kill\` is a *different* guard from the
delay, not a substitute for it: a stopped Session cannot rewrite its report, so
a killed lane's file is settled and you may retire it at once, while a lane left
running still wants the ~20 seconds before you delete anything.

\`\`\`bash
# Both lanes below started with no --cwd, so each Session runs at its Project
# root and the lane path is the prompt's path unchanged. A lane started at
# <project-root>/apps/api would instead read
#   7f3a=api:apps/api/.actana/reports/api-r1.md
bash await.sh --out ./reports --timeout 1800 \\
  7f3a=api:.actana/reports/api-r1.md \\
  9c1b=web:.actana/reports/web-r1.md
\`\`\`

A lane is \`<session-id>=<project>:<report-path>\`, and the report path is the
**Project's**, exactly as \`actana project cp\` takes it — not the Session's, and
that is the one conversion this whole procedure asks of you. \`await.sh\` resolves
it against the Project root the Core reports, so a lane carrying a bare
prompt path from a Session started somewhere else inside the Project waits for a
file nobody is writing, and says so only when the round's budget runs out.

\`--core <name>\` passes through to every call it makes; \`--kill\` stops each
Session once its report is safely on this disk. It exits 0 when every lane's
report was saved and 1 when any lane's was not, and prints one line per lane
saying which.

It is installed without an executable bit, on purpose — run it as \`bash
await.sh\`. Read it before you extend it: the reasons for each of those four
behaviours are written at the top of the file, and each one is a failure that
has actually happened.

## Several Sessions at once

There is no batch verb. Provisioning N Sessions is N \`session start\` calls, and
that is deliberate: each one gets its own prompt, its own Harness and possibly
its own Project, and a Session that fails to start is one failure rather than a
failed batch.

The shape that works:

1. **Ask what is missing before starting anything.** How many Sessions, what
   each one is for, and which Project. If the operator said "three sessions,
   each focusing on three different things", the three things are theirs to
   name — do not invent a split and do not start work on a guess.
2. **Check \`harness ls\` once**, and use only \`available\` ids.
3. **Mint one report path per lane before you start anything, and put it in that
   lane's prompt** along with the sub-agent declaration. The paths are what make
   the round collectable, and minting them up front is what makes them unique:
   one \`<id>\` per lane, \`-r1\` for the first turn of each. Mint the lane's
   **collection** path in the same breath — the same string when the lane has no
   \`--cwd\`, and that directory in front of it when it has one.

   \`\`\`bash
   actana session start "$project" "$prompt_a" --harness "$h_a" --json > a.json
   actana session start "$project" "$prompt_b" --harness "$h_b" --json > b.json
   actana session start "$project" "$prompt_c" --harness "$h_c" --json > c.json
   \`\`\`

   No \`--wait\` is needed here and none is wanted: \`start\` returns as soon as the
   Core has the Session running, so three starts in a row are three Sessions
   working side by side. Take each \`taskId\` out of its object.
4. **Wait for the files, not for the Sessions.** One loop over every
   outstanding lane — \`bash await.sh\` is that loop — polling each lane's
   **Project-relative** report path until its last line is \`ACT-REPORT-END\`,
   saving each one down as it lands. A lane that has not finished costs a lane
   that has nothing.
5. **\`logs\`, \`events tail\` and \`session ls\` are for watching progress, and that
   is all they are for.** A row's \`live\` field says whether the harness process
   is still up and its transcript still exists; a terminal status is not
   permission to treat a transcript as a result, and neither is \`live: true\`.
   The result is the file. If a Session reached a terminal status and no report
   file ever appeared, that is a lane that produced nothing — report it as
   exactly that.
6. **Report per Session, by id**, including the ones that produced no report. A
   Session that finished without one is a fact, not a gap to fill in.

**How many to start is the operator's decision, not a rule.** Every Session is a
Harness process on somebody's machine costing somebody's tokens. Start the
number that was asked for; if no number was asked for, ask.

**One level, and one only.** The Sessions you start are sub-agents, and the
skill they wake with forbids them starting Sessions of their own. Recursive
provisioning is unbounded — each level multiplies and nothing caps depth or
breadth — so the round you are running is the whole tree.

## When something is wrong

- **\`no Core registered\` / nothing from \`core ls\`** — this machine has no Core
  of its own and has not been pointed at a remote one. Pairing a remote Core is
  the operator's to do (\`actana core pair\`, with a code from \`actana pair new\`
  on the Core); say so rather than attempting it.
  Note that a machine running a Core registers it automatically, so an empty
  \`core ls\` means there is no local Core either — not that somebody forgot to
  pair one.
- **\`harness ls\` shows everything \`missing\`** — the Core has no coding agent
  installed. \`actana harness install <id>\` asks the Core to install one and
  waits for its verdict; it takes minutes and can legitimately fail.
- **A Session started but produced nothing** — check \`reportsTurnStart\` in the
  start object. When it is \`false\`, the Harness sends no turn-start signal and
  a Session can sit on \`ready\` through its whole first turn; wait on the report
  file rather than on the Session looking busy.
- **The report file never appears** — read the transcript with
  \`actana session logs <id>\` while the row still says \`live: true\` and find out
  what the Session did instead. The usual cause is a prompt that never stated
  the path, or stated one the Session could not create. Send the path again as a
  follow-up turn, with its own \`-r<turn>\` name; do not reuse the one that failed.
- **A report file is there but its last line is something else** — it is not
  finished. That is not an error and not a reason to read it: keep polling, and
  let the round's timeout be what gives up.
- **\`session logs\` says the Session has no harness running** — the Harness has
  exited and its transcript is gone with it. Nothing recovers a transcript. A
  report file that was written survives it, which is the point of writing one.
- **A prompt seems not to have arrived** — do not retype it and do not send a
  bare carriage return. Delivery is the Core's job; a lost prompt is a bug to
  report with the Session's id, not a thing to work around from here.
`,
    "await.sh": `#!/usr/bin/env bash
# x-actana-managed: true
#
# Wait for several Sessions' report files at once, save each one locally, and
# say per Session what happened.
#
# The marker on line 2 is the same marker \`SKILL.md\` carries in its frontmatter,
# and it means the same thing: this file was written by \`actana\` and \`actana\`
# will replace it, edits and all. Delete that line and this copy becomes yours —
# the installer reads the marker as a substring of a file's first bytes rather
# than through a YAML parser, so the escape hatch works here exactly as it works
# on the markdown.
#
# Run it with \`bash await.sh\` — it is installed without an executable bit, on
# purpose. The installer's whole safety argument is that it is a filesystem
# write and nothing else, and a write that also flips a permission bit is a
# larger act for no gain.
#
#   bash await.sh --out ./reports \\
#     7f3a=api:.actana/reports/api-r1.md 9c1b=web:.actana/reports/web-r1.md
#
# ── Why this is a file and not four paragraphs of advice ──────────────────────
#
# Four things go wrong when this loop is re-derived inline, and each of them has
# gone wrong. They are the reason the script ships:
#
#  1. **The LAST line is the proof; a grep is not.** \`ACT-REPORT-END\` occurring
#     anywhere in a report — quoted, in an example, inside a diff — settles a
#     Session that has not finished. This reads the tail of the file and
#     compares its last non-blank line to the sentinel. Nothing else counts.
#  2. **Save locally before deleting anything.** The report is copied down and
#     confirmed on this disk before the Session is killed. Delete-then-save is
#     the screen-era failure wearing a new mechanism.
#  3. **Every Session waits in ONE loop.** A per-Session wait serialises the
#     round: a slow lane blocks fast ones that finished minutes ago, and a
#     six-lane round then runs at the speed of its worst lane *summed* rather
#     than its worst lane alone. One loop polls every unfinished lane per tick.
#  4. **A dropped link is "not yet", never failure.** \`actana core exec\` exits
#     125 when the link to the Core went away mid-command: the command kept
#     running over there and this side has no result. A watcher that read 125 as
#     "the report is not there" would abandon a lane that is perfectly fine.
#
# ── What it needs ────────────────────────────────────────────────────────────
#
# \`actana\` on PATH and a Core selected (or \`--core <name>\`). \`node\` too, only to
# read one field out of \`actana project ls --json\` — it ships with the CLI, so
# this adds no dependency the CLI has not already made.

set -uo pipefail

SENTINEL="ACT-REPORT-END"
OUT_DIR="."
TIMEOUT=1800
INTERVAL=15
KILL_AFTER=0
CORE_ARGS=()

usage() {
  cat <<'USAGE'
bash await.sh [options] <lane>...

  lane            <session-id>=<project>:<report-path>
                  the report path is the Project's, exactly as \`project cp\`
                  takes it — \`7f3a=api:.actana/reports/api-r1.md\`

  --out <dir>     where saved reports land. Default: .
  --timeout <s>   give up on the round after this long. Default: 1800
  --interval <s>  seconds between polls. Default: 15
  --sentinel <s>  the last line that means "finished". Default: ACT-REPORT-END
  --kill          kill each Session once its report is safely on this disk
  --core <name>   which Core, passed through to every \`actana\` call
  -h, --help      this

Exits 0 when every lane's report was saved, 1 when any lane was not.
USAGE
}

LANE_SESSION=()
LANE_PROJECT=()
LANE_REMOTE=()
LANE_LOCAL=()
LANE_STATE=()
LANE_NOTE=()

# A value-taking flag with nothing after it is an error, and has to be said out
# loud. \`shift 2\` with one argument left shifts nothing and returns non-zero;
# nothing reads that status, so the same branch matched forever and the script
# hung with no output — a symptom indistinguishable from waiting on a Session
# that is still working. The caller here is a model composing a command line,
# and a silent hang is the worst thing it can be handed.
need_value() {
  # $1 is the flag; $2 is how many arguments are still unparsed, this one
  # included. Counting is the check: \`\${2:-}\` would turn a missing operand into
  # an empty string, which is what hid this in the first place.
  [ "$2" -ge 2 ] && return 0
  echo "await.sh: $1 needs a value" >&2
  usage >&2
  exit 2
}

while [ $# -gt 0 ]; do
  case "$1" in
    --out) need_value "$1" "$#"; OUT_DIR="$2"; shift 2 ;;
    --timeout) need_value "$1" "$#"; TIMEOUT="$2"; shift 2 ;;
    --interval) need_value "$1" "$#"; INTERVAL="$2"; shift 2 ;;
    --sentinel) need_value "$1" "$#"; SENTINEL="$2"; shift 2 ;;
    --core) need_value "$1" "$#"; CORE_ARGS=(--core "$2"); shift 2 ;;
    --kill) KILL_AFTER=1; shift ;;
    -h|--help) usage; exit 0 ;;
    --) shift; break ;;
    -*) echo "await.sh: unknown option \\"$1\\"" >&2; usage >&2; exit 2 ;;
    *) break ;;
  esac
done

if [ $# -eq 0 ]; then
  echo "await.sh: name at least one lane — <session-id>=<project>:<report-path>" >&2
  usage >&2
  exit 2
fi

for lane in "$@"; do
  session="\${lane%%=*}"
  ref="\${lane#*=}"
  if [ "$session" = "$lane" ] || [ -z "$session" ] || [ -z "$ref" ]; then
    echo "await.sh: \\"$lane\\" is not <session-id>=<project>:<report-path>" >&2
    exit 2
  fi
  project="\${ref%%:*}"
  remote="\${ref#*:}"
  if [ "$project" = "$ref" ] || [ -z "$project" ] || [ -z "$remote" ]; then
    echo "await.sh: \\"$ref\\" is not <project>:<report-path>" >&2
    exit 2
  fi
  # The destination carries the Session id, because the basename alone does not
  # identify a lane. "Three Sessions, each on a different thing" naturally gives
  # every sub-agent the same report filename inside its own Project, and two
  # lanes writing \`report.md\` into one directory would overwrite each other,
  # report \`saved\` twice naming the same file, and under --kill destroy both
  # Sessions — so the second lane's bytes were saved and the first lane's were
  # lost anyway. That is the failure "save before deleting" exists to prevent,
  # arriving by a different route.
  safe_session="$(printf '%s' "$session" | tr -c 'A-Za-z0-9._-' '_')"
  LANE_SESSION+=("$session")
  LANE_PROJECT+=("$project")
  LANE_REMOTE+=("$remote")
  LANE_LOCAL+=("$OUT_DIR/\${safe_session}-$(basename "$remote")")
  LANE_STATE+=("waiting")
  LANE_NOTE+=("no report yet")
done

# Prefixing makes a collision unlikely, not impossible: one Session writing two
# reports from different folders still lands on one name. So the remaining case
# is refused here, before a single Session is touched — a usage error costs a
# retype, and a silently discarded report costs the work that produced it.
for i in "\${!LANE_LOCAL[@]}"; do
  for j in "\${!LANE_LOCAL[@]}"; do
    [ "$i" -lt "$j" ] || continue
    [ "\${LANE_LOCAL[$i]}" = "\${LANE_LOCAL[$j]}" ] || continue
    echo "await.sh: \${LANE_SESSION[$i]} and \${LANE_SESSION[$j]} would both be saved as" >&2
    echo "  \${LANE_LOCAL[$i]}" >&2
    echo "Give them different report filenames, or a --out directory each." >&2
    exit 2
  done
done

mkdir -p "$OUT_DIR" || exit 1

# The Project's path on the Core, so the tail below can name an absolute file.
# Read once per Project rather than per tick: a Project's path is fixed for the
# life of the Project — no verb edits one — so re-reading it every 15 seconds
# would be asking a settled question over and over.
project_root() {
  actana project ls --json "\${CORE_ARGS[@]+"\${CORE_ARGS[@]}"}" 2>/dev/null |
    node -e '
      let raw = "";
      process.stdin.on("data", (chunk) => (raw += chunk));
      process.stdin.on("end", () => {
        let rows = [];
        try { rows = JSON.parse(raw); } catch { process.exit(1); }
        const want = process.argv[1];
        const hit = rows.find((row) => row.name === want || row.projectId === want);
        if (!hit || !hit.path) process.exit(1);
        process.stdout.write(hit.path);
      });
    ' "$1"
}

ROOTS=()
for index in "\${!LANE_PROJECT[@]}"; do
  root="$(project_root "\${LANE_PROJECT[$index]}")"
  if [ -z "$root" ]; then
    echo "await.sh: no Project named \\"\${LANE_PROJECT[$index]}\\" on this Core" >&2
    exit 1
  fi
  ROOTS+=("$root")
done

# Lesson 1. The sentinel has to be the file's LAST line, so this reads the tail
# and nothing else. A few lines rather than exactly one, because a trailing
# blank line an editor left behind is not a Session that failed to finish — and
# a sentinel quoted in the body of the report is still nowhere near the tail.
last_line_is_sentinel() {
  local tail_text="$1" line last=""
  while IFS= read -r line; do
    line="\${line#"\${line%%[![:space:]]*}"}"
    line="\${line%"\${line##*[![:space:]]}"}"
    [ -n "$line" ] && last="$line"
  done <<EOF
$tail_text
EOF
  [ "$last" = "$SENTINEL" ]
}

started="$(date +%s)"
pending="\${#LANE_SESSION[@]}"

echo "await.sh: watching $pending lane(s) for a last line of \\"$SENTINEL\\"" >&2

# Lesson 3. ONE loop, every unfinished lane per tick. Nothing here blocks on a
# single Session, which is what keeps a six-lane round running at the speed of
# its slowest lane rather than the sum of all six.
while [ "$pending" -gt 0 ]; do
  now="$(date +%s)"
  if [ $((now - started)) -ge "$TIMEOUT" ]; then
    for index in "\${!LANE_SESSION[@]}"; do
      [ "\${LANE_STATE[$index]}" = "waiting" ] || continue
      LANE_STATE[$index]="timeout"
      # Carry the last thing this lane saw into the timeout line. "The budget
      # ran out" and "the budget ran out while the link kept dropping" are
      # different reports, and the second one is about the network.
      LANE_NOTE[$index]="the round's \${TIMEOUT}s budget ran out — the Session is still running; last: \${LANE_NOTE[$index]}"
    done
    break
  fi

  for index in "\${!LANE_SESSION[@]}"; do
    [ "\${LANE_STATE[$index]}" = "waiting" ] || continue

    remote_path="\${ROOTS[$index]}/\${LANE_REMOTE[$index]}"
    tail_text="$(actana core exec "\${CORE_ARGS[@]+"\${CORE_ARGS[@]}"}" -- tail -n 3 -- "$remote_path" 2>/dev/null)"
    status=$?

    # Lesson 4. 125 is EXIT_LINK_LOST: the tail kept running on the Core and
    # this side has no answer. That is "ask again next tick", never "no report".
    if [ "$status" -eq 125 ]; then
      LANE_NOTE[$index]="the link to the Core dropped mid-poll — retrying, not giving up"
      continue
    fi
    # Any other non-zero is almost always "the file is not there yet", which is
    # the ordinary state of a Session that is still working.
    [ "$status" -eq 0 ] || continue
    LANE_NOTE[$index]="a report file is there, but its last line is not the sentinel yet"
    last_line_is_sentinel "$tail_text" || continue

    # Lesson 2. Save first. The Session is not touched until the bytes are on
    # this disk and the file we wrote is non-empty.
    local_path="\${LANE_LOCAL[$index]}"
    if ! actana project cp "\${CORE_ARGS[@]+"\${CORE_ARGS[@]}"}" \\
      "\${LANE_PROJECT[$index]}:\${LANE_REMOTE[$index]}" "$local_path" >/dev/null 2>&1; then
      LANE_STATE[$index]="failed"
      LANE_NOTE[$index]="the report finished but could not be copied down — it is still on the Core"
      pending=$((pending - 1))
      continue
    fi
    if [ ! -s "$local_path" ]; then
      LANE_STATE[$index]="failed"
      LANE_NOTE[$index]="the copy landed empty — the report is still on the Core, nothing was killed"
      pending=$((pending - 1))
      continue
    fi

    LANE_STATE[$index]="saved"
    LANE_NOTE[$index]="$local_path"
    pending=$((pending - 1))

    if [ "$KILL_AFTER" -eq 1 ]; then
      if actana session kill "\${CORE_ARGS[@]+"\${CORE_ARGS[@]}"}" "\${LANE_SESSION[$index]}" >/dev/null 2>&1; then
        LANE_NOTE[$index]="$local_path (Session killed)"
      else
        LANE_NOTE[$index]="$local_path (saved; the Session would not stop — kill it by hand)"
      fi
    fi
  done

  [ "$pending" -gt 0 ] && sleep "$INTERVAL"
done

failures=0
for index in "\${!LANE_SESSION[@]}"; do
  printf '%s\\t%s\\t%s\\n' "\${LANE_SESSION[$index]}" "\${LANE_STATE[$index]}" "\${LANE_NOTE[$index]}"
  [ "\${LANE_STATE[$index]}" = "saved" ] || failures=$((failures + 1))
done

# A lane that produced nothing is a fact to report, not a gap to fill in.
exit $([ "$failures" -eq 0 ] && echo 0 || echo 1)
`,
  },
  "actana-subagent": {
    "SKILL.md": `---
name: actana-subagent
description: Hand work back as a sub-agent of an orchestrating Session — write the report file the orchestrating Session named, ending it with the exact final line that marks it complete, and provision no further Sessions. Use whenever a prompt says this Session is acting as a sub-agent of an orchestrating Session, or names a report file for this Session to write and an end marker to finish it with.
x-actana-managed: true
---

# Reporting back as a sub-agent

A prompt has told this Session that it is acting as a **sub-agent** of an
orchestrating Session. That declaration is what turned this skill on, and it
means one concrete thing: the Session that woke you is waiting on a **file**,
not on your screen, and it cannot see anything you print.

**This skill is eager, and the one installed beside it — the orchestrator skill
— is invoke-only. The asymmetry is deliberate; do not tidy it into symmetry.**
The orchestrator role is a thing an operator asks for, so that skill waits to
be asked. The sub-agent role is a thing a Session is *told it already is*, by
the prompt that woke it, and there is no operator in that loop to ask. One
\`description\` field cannot hold both requirements, which is why these are two
files.

**This skill covers two things and nothing else: the report file, and the
prohibition below.** It says nothing about how to do the work — not the
planning, not the implementation, not the testing, not what to put in the
report. That silence is deliberate and it is a bound, not an omission. An
orchestrating Session routinely passes other skills in the same prompt, and
this one is eager while those were invoked: advice from here would fight them
and would win. Whatever the prompt asked for, and whatever skill it named, is
what governs the work. This governs only how the answer gets back.

## The report file

- **The path is \`.actana/reports/<id>-r<turn>.md\`, relative to this Session's
  own working directory — its \`cwd\` on the machine it is running on.** Create
  \`.actana/reports\` if it is not there. It is dot-prefixed because it is machine
  state rather than project content. Write it exactly where the prompt said,
  and do not helpfully move it somewhere tidier: the Session that woke you
  converts that path into one it can read back, and a file at a different place
  is a file nobody collects.
- **The orchestrating Session mints the name, and it states the full relative
  path in its prompt, every turn.** Use exactly the path you were given.
  **Never invent one, never shorten one, and never reuse a path from an earlier
  turn** — the name carries a turn number precisely so that turn 2 cannot be
  read as turn 1's report. If a turn's prompt names no path, say so in the
  Session and write nothing rather than guessing at a name nobody is watching.
- **The file's final line must be exactly \`ACT-REPORT-END\`**, on its own line,
  with nothing after it.

That last line is the whole settling signal. The Session waiting on you polls
the file and compares its **last** line to that marker: no status, no event and
no timeout tells it you are done, and nothing else will. Two consequences, and
both of them bite:

- **Write the file only when the report is complete.** A file whose last line is
  anything else reads as "still working", which is correct while you are — but a
  half-written file left behind by an abandoned attempt is a lane that never
  settles.
- **Print nothing that matters only to the screen.** Whatever you say in the
  Session is read by a person, if anybody reads it at all. The file is the
  answer.

Do not write to a temporary name and rename it into place. It is better
engineering and worse instruction-following: the second step is the one that
gets skipped, and a temporary file that never lands is a lane that never
settles. One file, written once, ending in the marker.

## Do not create Sessions

**A sub-agent must not start Sessions of its own through the \`actana\` CLI.** Not
on this Core, not on another one, not for a piece of the work that would divide
neatly. \`actana session start\` is the orchestrating Session's to call and not
yours. If the work genuinely needs more Sessions, say so in your report and let
the Session that woke you decide.

The bound is recursion. Every level of provisioning multiplies the level below
it, nothing caps the depth or the breadth of that, and every Session is a
harness process costing somebody's tokens on somebody's machine. One
orchestrating Session, one level of sub-agents.

**This does not restrict a harness's own native sub-agent facility.** If the
coding agent you are running inside has an in-process task or sub-agent
mechanism of its own, it stays available and this skill has nothing to say about
it: that is a different mechanism with different bounds, and it provisions
nothing on any Core. The prohibition is about \`actana session start\`, and about
nothing else.
`,
  },
};
