// GENERATED by scripts/gen-skill-payload.mjs — do not edit.
//
// The source is `.agents/skills/actana-sessions/`, and
// `packages/shared/src/__tests__/orchestration-skill-fanout.test.ts` — the one
// drift test, in the one package that can read both copies — fails when the two
// disagree. Edit the authored files, re-run the generator, commit both.
// ADR 0031 D8 is why this is embedded rather than read off disk.

/** The skill's directory name — its address in a harness's skills root. */
export const ORCHESTRATION_SKILL_NAME = "actana-sessions";

/**
 * The in-band marker that makes a copy ours (ADR 0031 D1).
 *
 * The authorisation to overwrite, and the operator's escape hatch: delete this
 * line from a copy and the installer never touches that file again. It is
 * matched as a substring of a file's first bytes rather than as a parsed key,
 * which is why the same marker works in `SKILL.md`'s frontmatter and in a
 * shell script's second line.
 */
export const ORCHESTRATION_SKILL_MARKER = "x-actana-managed: true";

/**
 * The authored skill folder, byte for byte: folder-relative path to contents.
 *
 * Keys are `/`-separated on every platform — the installer splits them before
 * joining. Every value carries the marker above; the generator refuses to emit
 * one that does not.
 *
 * Typed as a plain record rather than left to infer its literal keys: a file
 * name in here is data the installer is handed, never an identifier anything
 * branches on, and a type that made `"SKILL.md"` special would be the first
 * step towards code that treats it that way.
 */
export const ORCHESTRATION_SKILL_FILES: Readonly<Record<string, string>> = {
  "SKILL.md": `---
name: actana-sessions
description: Drive Actana Control Cores and Sessions with the \`actana\` CLI — register and select a Core, see which Harnesses it can run, start Sessions with a prompt, wait for them to settle, read what they produced, send follow-up input, and stop them. Use when asked to run work in one or more Sessions, to provision several Sessions at once ("give me three sessions, each on a different thing"), to check on or collect results from Sessions already running, or whenever a task would be done by another agent on a Core rather than here.
x-actana-managed: true
---

# Driving Cores and Sessions with \`actana\`

\`actana\` is a client. A **Core** is a machine running the Actana Control daemon;
a **Session** is one Harness process — a vendor's coding agent — running on that
Core inside a **Project**. Sessions belong to the Core, not to this command: a
Session keeps running after \`actana\` exits, and any later \`actana\` invocation
can list it, read it, write to it or stop it.

If \`actana\` is not on this machine, or reports no Core, say so and stop. Do not
install anything and do not guess at a Core's address.

## Orientation, in the order that answers the questions

\`\`\`bash
actana core ls                 # Cores this machine can reach; * marks the selected one
actana core use <name>         # select one for subsequent commands
actana harness ls --json       # what the selected Core can actually run, right now
actana project ls --json       # the Projects on that Core; a Session needs one
actana session ls --json       # Sessions already running there
\`\`\`

\`--core <name>\` overrides the selection for a single command. Every list verb
takes \`--json\`, and under \`--json\` only the JSON document reaches stdout —
diagnostics go to stderr — so parsing is safe.

**On a machine that is itself a Core, that Core is already registered and
already selected.** Installing a Core wires it to the same machine's \`actana\`,
so \`core ls\` lists it and it is what every command below means unless \`--core\`
or \`core use\` says otherwise. Address it by default; do not ask the operator to
pair the machine you are already standing on.

**Pick the Harness from what \`harness ls\` reports, every time.** It lists each
Harness with a \`status\` of \`available\` or \`missing\`; only \`available\` can run.
There is no default and no preference order here on purpose — operators have
their own, this skill has none, and a Harness that was available yesterday may
be missing today. Ask the operator if the choice matters to them and nothing in
the request settles it.

## Starting one Session

\`\`\`bash
actana session start <project> "<prompt>"            # prints the session id, exits
actana session start <project> "<prompt>" --json     # the same as an object
actana session start <project> - < brief.md          # a prompt of \`-\` is read from stdin
\`\`\`

Useful flags: \`--harness <id>\` (one of the ids \`harness ls\` printed),
\`--title <text>\` (what it is called in a listing), \`--cwd <path>\` (a directory
**on the Core**, inside the Project), \`--dangerously-skip-permissions\` (run the
Harness without permission prompts — only when the operator has asked for
unattended work).

\`start\` returns as soon as the Core has the Session running. The prompt is
delivered by the Core, which watches the Harness boot and types when it is
ready; add no delays, no leading newline and no "press enter" of your own.

## Waiting, and reading the result

\`\`\`bash
actana session start <project> "<prompt>" --wait --json --wait-timeout 900
\`\`\`

**\`--wait --json\` is the reliable way to collect a result, and the reason is
mechanical.** A Session's transcript lives in a replay ring that belongs to the
Harness's terminal, so a Harness that has exited has taken its output with it
and a later \`actana session logs\` has nothing left to print. The object
\`--wait --json\` prints carries a \`screen\` field holding the transcript as it
settled, in the same document as the status — so the result is in hand before
the process it came from can disappear.

The object also carries \`taskId\` (the Session's id — this is what every other
verb takes), \`harness\`, \`project\`, \`status\`, \`exited\`, and \`reportsTurnStart\`.
\`--wait-timeout <seconds>\` bounds the wait; without it the wait has no deadline
of its own. A timeout is this side giving up, not a verdict about the Session:
the Session is still running on the Core and can still be listed, read and
stopped.

While a Session is alive — which is what the \`live\` field on its
\`actana session ls --json\` row tells you, and the only thing that does — you can
also look at it directly:

\`\`\`bash
actana session logs <id>          # the transcript, rendered, while the harness is running
actana session send <id> "text"   # write into it; --enter follows with a carriage return
actana session wait <id>          # block until the Core reports it settled
actana session kill <id>          # stop the harness running for it
\`\`\`

\`actana events tail --json\` follows the Core's event log as NDJSON if you want
to watch state change rather than poll — \`session:finished\` is the Core's own
signal that a Session reached a terminal state.

## The multi-turn loop

A Session is a conversation, not a single question. The whole loop:

\`\`\`bash
ID=$(actana session start <project> "<first prompt>")   # prints the id, exits
actana session wait "$ID" --json --wait-timeout 900     # block until it settles
actana session send "$ID" "<follow-up>" --enter --wait --json --wait-timeout 900
actana session logs "$ID"                               # or read \`screen\` off the object
actana session send "$ID" "<next>" --enter --wait --json
\`\`\`

**\`actana session wait <id>\` blocks until the Core reports the Session settled**
— \`finished\`, \`needs-input\`, \`interrupted\`, \`terminated\` or \`disconnected\`,
because every one of those is a turn that ended. A Session that is already
settled answers at once, so a wait that starts after the turn ended is not a
wait that hangs.

**\`actana session send <id> "<text>" --wait\` waits for the turn that text
starts.** The Core stamps the delivery in its event log and the wait resolves on
the first settling status *after* that stamp, so it can never hand you the
status the Session was already parked at. With \`--json\` it prints the **same
object** \`start --wait --json\` prints — same keys, same \`screen\` — so one parser
reads all three verbs. Two of those keys are \`null\` on a Session you attached to
rather than started: \`command\` and \`reportsTurnStart\` are answers to a spawn.

Three things to know before you build on it:

1. **Sending into a turn that is already running resolves on *that* turn's
   end.** A keystroke into a busy Harness is not a new turn. If the Session was
   mid-turn when your text landed, the wait ends when the current turn ends —
   possibly before the Harness has read a character of what you sent. Wait for
   the Session to settle *first*, then send.
2. **\`--enter\` is what submits the text.** \`send\` writes exactly the bytes it
   was given and appends nothing, so text with no return sits in the Harness's
   composer and no turn starts — and the wait then runs to your timeout.
3. **A timeout is this side giving up, not a status.** \`--wait-timeout
   <seconds>\` bounds the wait; without it there is no deadline, because a turn
   takes as long as the work takes. On expiry you get a message saying the wait
   gave up and a non-zero exit — the Session is still running on the Core, and
   \`session logs\`, another \`session wait\` and \`session kill\` all still work.

Do not poll \`actana session logs\` for a sentinel instead. It renders a
fixed-size screen: lines scroll off the top, so counting occurrences is not
monotonic, and a marker can match your own echoed prompt rather than the
Harness's reply.

## Asking a Session for a machine-readable report

A screen is a transcript, not a result. When you need a Session to hand back
something you can parse, tell it in the prompt to end with its report wrapped in
a sentinel pair, and take the report out of the settled screen.

The sentinel is \`<%ACT_REPORT%>\` … \`<%/ACT_REPORT%>\`, and the four rules matter
as much as the token:

1. **The token is deliberately unusual.** Ordinary prose, code samples and test
   fixtures never contain \`<%ACT_REPORT%>\`, so a match is a report and not a
   coincidence.
2. **It is a pair, not a single marker.** A lone marker is unrecoverable the
   moment the Harness prints anything after its report — there is no way to
   tell where the report ended.
3. **The last complete pair wins.** A conversation runs many turns and may emit
   the sentinel more than once; the pair nearest the end is the final state.
   An incomplete trailing opener is not a report.
4. **Match with whitespace stripped.** What you are reading is a *rendered
   screen*, produced by a terminal emulator with a fixed width, so a tag that
   reaches the right margin is wrapped across two rows and a literal match
   fails. Strip whitespace — newlines included — from both the haystack and the
   tags before searching, and keep the original text for the extracted body.

Put the instruction in the prompt itself, in the Session's own words:

> When you are finished, print your result between \`<%ACT_REPORT%>\` and
> \`<%/ACT_REPORT%>\` on their own lines, and print nothing after the closing tag.

**Save the report before you stop the Session.** Killing a Session destroys the
replay ring the report is being read from — collect first, kill second, in that
order, always.

## Several Sessions at once

There is no batch verb. Provisioning N Sessions is N \`session start\` calls, and
that is deliberate: each one gets its own prompt, its own Harness and possibly
its own Project, and a Session that fails to start is one failure rather than a
failed batch.

The shape that works:

1. **Ask what is missing before starting anything.** How many Sessions, what
   each one is for, and which Project. If the operator said "three sessions,
   each focusing on three different things", the three things are theirs to
   name — do not invent a split and do not start work on a guess.
2. **Check \`harness ls\` once**, and use only \`available\` ids.
3. **Start each Session in its own backgrounded \`--wait --json\` call, and wait
   for all of them together.** N concurrent Sessions are N \`session start
   --wait --json\` calls running side by side — that is what makes them
   concurrent, not the absence of \`--wait\`. Run them one after another and you
   have a queue; run them in the background and you have N settled \`screen\`
   fields, which is the only thing this CLI hands back that is guaranteed to
   still exist when you read it.

   \`\`\`bash
   actana session start "$project" "$prompt_a" --wait --json --wait-timeout 900 > a.json &
   actana session start "$project" "$prompt_b" --wait --json --wait-timeout 900 > b.json &
   actana session start "$project" "$prompt_c" --wait --json --wait-timeout 900 > c.json &
   wait
   \`\`\`

   Each file holds one complete object: \`taskId\`, \`status\`, \`exited\` and the
   \`screen\` as it settled. Take every report out of those, not out of a later
   \`logs\` call.
4. **Give each one the sentinel instruction** in its prompt.
5. **If you polled instead, check \`live\` before you read anything.** Starting
   without \`--wait\` and polling \`actana session ls --json\` — or following
   \`actana events tail --json\` — is a legitimate shape when you want to watch
   progress, but a terminal status is not permission to read a transcript.
   Every \`session ls --json\` row carries a **\`live\`** field beside its status
   (it is the \`LIVE\` column in the table). \`live: true\` means the harness
   process is still up and its replay ring still holds the transcript;
   \`live: false\` means the harness has exited and took the transcript with it,
   whatever the status says. So: read \`actana session logs <id>\` only while
   that row says \`live: true\`, extract the last complete sentinel pair, and
   only then \`actana session kill <id>\`. A row that reached a terminal status
   with \`live: false\` before you got to it is a result you did not collect —
   report it as that, and use \`--wait --json\` for the next run rather than
   trying to recover it. This is the whole reason step 3 is written the way it
   is: polling races the process, and \`--wait --json\` does not.
6. **Report per Session, by id**, including the ones that produced no parseable
   report. A Session that finished without a report is a fact, not a gap to
   fill in.

**How many to start is the operator's decision, not a rule.** Every Session is a
Harness process on somebody's machine costing somebody's tokens. Start the
number that was asked for; if no number was asked for, ask.

## When something is wrong

- **\`no Core registered\` / nothing from \`core ls\`** — this machine has no Core
  of its own and has not been pointed at a remote one. Pairing a remote Core is
  the operator's to do (\`actana core pair\`, with a code from \`actana pair new\`
  on the Core); say so rather than attempting it.
  Note that a machine running a Core registers it automatically, so an empty
  \`core ls\` means there is no local Core either — not that somebody forgot to
  pair one.
- **\`harness ls\` shows everything \`missing\`** — the Core has no coding agent
  installed. \`actana harness install <id>\` asks the Core to install one and
  waits for its verdict; it takes minutes and can legitimately fail.
- **A Session started but produced nothing** — check \`reportsTurnStart\` in the
  start object. When it is \`false\`, the Harness sends no turn-start signal and
  a Session can sit on \`ready\` through its whole first turn; wait on the
  Session's terminal status rather than on it looking busy.
- **\`session logs\` says the Session has no harness running** — the Harness has
  exited and its transcript is gone with it. Nothing recovers it. That is what
  \`--wait --json\` exists to prevent, next time. The same fact is visible before
  you read: the Session's row in \`actana session ls --json\` says \`live: false\`.
- **A prompt seems not to have arrived** — do not retype it and do not send a
  bare carriage return. Delivery is the Core's job; a lost prompt is a bug to
  report with the Session's id, not a thing to work around from here.
`,
  "await.sh": `#!/usr/bin/env bash
# x-actana-managed: true
#
# Wait for several Sessions' report files at once, save each one locally, and
# say per Session what happened.
#
# The marker on line 2 is the same marker \`SKILL.md\` carries in its frontmatter,
# and it means the same thing: this file was written by \`actana\` and \`actana\`
# will replace it, edits and all. Delete that line and this copy becomes yours —
# the installer reads the marker as a substring of a file's first bytes rather
# than through a YAML parser, so the escape hatch works here exactly as it works
# on the markdown.
#
# Run it with \`bash await.sh\` — it is installed without an executable bit, on
# purpose. The installer's whole safety argument is that it is a filesystem
# write and nothing else, and a write that also flips a permission bit is a
# larger act for no gain.
#
#   bash await.sh --out ./reports 7f3a=api:reports/a.md 9c1b=api:reports/b.md
#
# ── Why this is a file and not four paragraphs of advice ──────────────────────
#
# Four things go wrong when this loop is re-derived inline, and each of them has
# gone wrong. They are the reason the script ships:
#
#  1. **The LAST line is the proof; a grep is not.** \`ACT-REPORT-END\` occurring
#     anywhere in a report — quoted, in an example, inside a diff — settles a
#     Session that has not finished. This reads the tail of the file and
#     compares its last non-blank line to the sentinel. Nothing else counts.
#  2. **Save locally before deleting anything.** The report is copied down and
#     confirmed on this disk before the Session is killed. Delete-then-save is
#     the screen-era failure wearing a new mechanism.
#  3. **Every Session waits in ONE loop.** A per-Session wait serialises the
#     round: a slow lane blocks fast ones that finished minutes ago, and a
#     six-lane round then runs at the speed of its worst lane *summed* rather
#     than its worst lane alone. One loop polls every unfinished lane per tick.
#  4. **A dropped link is "not yet", never failure.** \`actana core exec\` exits
#     125 when the link to the Core went away mid-command: the command kept
#     running over there and this side has no result. A watcher that read 125 as
#     "the report is not there" would abandon a lane that is perfectly fine.
#
# ── What it needs ────────────────────────────────────────────────────────────
#
# \`actana\` on PATH and a Core selected (or \`--core <name>\`). \`node\` too, only to
# read one field out of \`actana project ls --json\` — it ships with the CLI, so
# this adds no dependency the CLI has not already made.

set -uo pipefail

SENTINEL="ACT-REPORT-END"
OUT_DIR="."
TIMEOUT=1800
INTERVAL=15
KILL_AFTER=0
CORE_ARGS=()

usage() {
  cat <<'USAGE'
bash await.sh [options] <lane>...

  lane            <session-id>=<project>:<report-path>
                  the report path is the Project's, exactly as \`project cp\`
                  takes it — \`7f3a=api:reports/impl-304-r1.md\`

  --out <dir>     where saved reports land. Default: .
  --timeout <s>   give up on the round after this long. Default: 1800
  --interval <s>  seconds between polls. Default: 15
  --sentinel <s>  the last line that means "finished". Default: ACT-REPORT-END
  --kill          kill each Session once its report is safely on this disk
  --core <name>   which Core, passed through to every \`actana\` call
  -h, --help      this

Exits 0 when every lane's report was saved, 1 when any lane was not.
USAGE
}

LANE_SESSION=()
LANE_PROJECT=()
LANE_REMOTE=()
LANE_LOCAL=()
LANE_STATE=()
LANE_NOTE=()

# A value-taking flag with nothing after it is an error, and has to be said out
# loud. \`shift 2\` with one argument left shifts nothing and returns non-zero;
# nothing reads that status, so the same branch matched forever and the script
# hung with no output — a symptom indistinguishable from waiting on a Session
# that is still working. The caller here is a model composing a command line,
# and a silent hang is the worst thing it can be handed.
need_value() {
  # $1 is the flag; $2 is how many arguments are still unparsed, this one
  # included. Counting is the check: \`\${2:-}\` would turn a missing operand into
  # an empty string, which is what hid this in the first place.
  [ "$2" -ge 2 ] && return 0
  echo "await.sh: $1 needs a value" >&2
  usage >&2
  exit 2
}

while [ $# -gt 0 ]; do
  case "$1" in
    --out) need_value "$1" "$#"; OUT_DIR="$2"; shift 2 ;;
    --timeout) need_value "$1" "$#"; TIMEOUT="$2"; shift 2 ;;
    --interval) need_value "$1" "$#"; INTERVAL="$2"; shift 2 ;;
    --sentinel) need_value "$1" "$#"; SENTINEL="$2"; shift 2 ;;
    --core) need_value "$1" "$#"; CORE_ARGS=(--core "$2"); shift 2 ;;
    --kill) KILL_AFTER=1; shift ;;
    -h|--help) usage; exit 0 ;;
    --) shift; break ;;
    -*) echo "await.sh: unknown option \\"$1\\"" >&2; usage >&2; exit 2 ;;
    *) break ;;
  esac
done

if [ $# -eq 0 ]; then
  echo "await.sh: name at least one lane — <session-id>=<project>:<report-path>" >&2
  usage >&2
  exit 2
fi

for lane in "$@"; do
  session="\${lane%%=*}"
  ref="\${lane#*=}"
  if [ "$session" = "$lane" ] || [ -z "$session" ] || [ -z "$ref" ]; then
    echo "await.sh: \\"$lane\\" is not <session-id>=<project>:<report-path>" >&2
    exit 2
  fi
  project="\${ref%%:*}"
  remote="\${ref#*:}"
  if [ "$project" = "$ref" ] || [ -z "$project" ] || [ -z "$remote" ]; then
    echo "await.sh: \\"$ref\\" is not <project>:<report-path>" >&2
    exit 2
  fi
  # The destination carries the Session id, because the basename alone does not
  # identify a lane. "Three Sessions, each on a different thing" naturally gives
  # every sub-agent the same report filename inside its own Project, and two
  # lanes writing \`report.md\` into one directory would overwrite each other,
  # report \`saved\` twice naming the same file, and under --kill destroy both
  # Sessions — so the second lane's bytes were saved and the first lane's were
  # lost anyway. That is the failure "save before deleting" exists to prevent,
  # arriving by a different route.
  safe_session="$(printf '%s' "$session" | tr -c 'A-Za-z0-9._-' '_')"
  LANE_SESSION+=("$session")
  LANE_PROJECT+=("$project")
  LANE_REMOTE+=("$remote")
  LANE_LOCAL+=("$OUT_DIR/\${safe_session}-$(basename "$remote")")
  LANE_STATE+=("waiting")
  LANE_NOTE+=("no report yet")
done

# Prefixing makes a collision unlikely, not impossible: one Session writing two
# reports from different folders still lands on one name. So the remaining case
# is refused here, before a single Session is touched — a usage error costs a
# retype, and a silently discarded report costs the work that produced it.
for i in "\${!LANE_LOCAL[@]}"; do
  for j in "\${!LANE_LOCAL[@]}"; do
    [ "$i" -lt "$j" ] || continue
    [ "\${LANE_LOCAL[$i]}" = "\${LANE_LOCAL[$j]}" ] || continue
    echo "await.sh: \${LANE_SESSION[$i]} and \${LANE_SESSION[$j]} would both be saved as" >&2
    echo "  \${LANE_LOCAL[$i]}" >&2
    echo "Give them different report filenames, or a --out directory each." >&2
    exit 2
  done
done

mkdir -p "$OUT_DIR" || exit 1

# The Project's path on the Core, so the tail below can name an absolute file.
# Read once per Project rather than per tick: a Project's path is fixed for the
# life of the Project — no verb edits one — so re-reading it every 15 seconds
# would be asking a settled question over and over.
project_root() {
  actana project ls --json "\${CORE_ARGS[@]+"\${CORE_ARGS[@]}"}" 2>/dev/null |
    node -e '
      let raw = "";
      process.stdin.on("data", (chunk) => (raw += chunk));
      process.stdin.on("end", () => {
        let rows = [];
        try { rows = JSON.parse(raw); } catch { process.exit(1); }
        const want = process.argv[1];
        const hit = rows.find((row) => row.name === want || row.projectId === want);
        if (!hit || !hit.path) process.exit(1);
        process.stdout.write(hit.path);
      });
    ' "$1"
}

ROOTS=()
for index in "\${!LANE_PROJECT[@]}"; do
  root="$(project_root "\${LANE_PROJECT[$index]}")"
  if [ -z "$root" ]; then
    echo "await.sh: no Project named \\"\${LANE_PROJECT[$index]}\\" on this Core" >&2
    exit 1
  fi
  ROOTS+=("$root")
done

# Lesson 1. The sentinel has to be the file's LAST line, so this reads the tail
# and nothing else. A few lines rather than exactly one, because a trailing
# blank line an editor left behind is not a Session that failed to finish — and
# a sentinel quoted in the body of the report is still nowhere near the tail.
last_line_is_sentinel() {
  local tail_text="$1" line last=""
  while IFS= read -r line; do
    line="\${line#"\${line%%[![:space:]]*}"}"
    line="\${line%"\${line##*[![:space:]]}"}"
    [ -n "$line" ] && last="$line"
  done <<EOF
$tail_text
EOF
  [ "$last" = "$SENTINEL" ]
}

started="$(date +%s)"
pending="\${#LANE_SESSION[@]}"

echo "await.sh: watching $pending lane(s) for a last line of \\"$SENTINEL\\"" >&2

# Lesson 3. ONE loop, every unfinished lane per tick. Nothing here blocks on a
# single Session, which is what keeps a six-lane round running at the speed of
# its slowest lane rather than the sum of all six.
while [ "$pending" -gt 0 ]; do
  now="$(date +%s)"
  if [ $((now - started)) -ge "$TIMEOUT" ]; then
    for index in "\${!LANE_SESSION[@]}"; do
      [ "\${LANE_STATE[$index]}" = "waiting" ] || continue
      LANE_STATE[$index]="timeout"
      # Carry the last thing this lane saw into the timeout line. "The budget
      # ran out" and "the budget ran out while the link kept dropping" are
      # different reports, and the second one is about the network.
      LANE_NOTE[$index]="the round's \${TIMEOUT}s budget ran out — the Session is still running; last: \${LANE_NOTE[$index]}"
    done
    break
  fi

  for index in "\${!LANE_SESSION[@]}"; do
    [ "\${LANE_STATE[$index]}" = "waiting" ] || continue

    remote_path="\${ROOTS[$index]}/\${LANE_REMOTE[$index]}"
    tail_text="$(actana core exec "\${CORE_ARGS[@]+"\${CORE_ARGS[@]}"}" -- tail -n 3 -- "$remote_path" 2>/dev/null)"
    status=$?

    # Lesson 4. 125 is EXIT_LINK_LOST: the tail kept running on the Core and
    # this side has no answer. That is "ask again next tick", never "no report".
    if [ "$status" -eq 125 ]; then
      LANE_NOTE[$index]="the link to the Core dropped mid-poll — retrying, not giving up"
      continue
    fi
    # Any other non-zero is almost always "the file is not there yet", which is
    # the ordinary state of a Session that is still working.
    [ "$status" -eq 0 ] || continue
    LANE_NOTE[$index]="a report file is there, but its last line is not the sentinel yet"
    last_line_is_sentinel "$tail_text" || continue

    # Lesson 2. Save first. The Session is not touched until the bytes are on
    # this disk and the file we wrote is non-empty.
    local_path="\${LANE_LOCAL[$index]}"
    if ! actana project cp "\${CORE_ARGS[@]+"\${CORE_ARGS[@]}"}" \\
      "\${LANE_PROJECT[$index]}:\${LANE_REMOTE[$index]}" "$local_path" >/dev/null 2>&1; then
      LANE_STATE[$index]="failed"
      LANE_NOTE[$index]="the report finished but could not be copied down — it is still on the Core"
      pending=$((pending - 1))
      continue
    fi
    if [ ! -s "$local_path" ]; then
      LANE_STATE[$index]="failed"
      LANE_NOTE[$index]="the copy landed empty — the report is still on the Core, nothing was killed"
      pending=$((pending - 1))
      continue
    fi

    LANE_STATE[$index]="saved"
    LANE_NOTE[$index]="$local_path"
    pending=$((pending - 1))

    if [ "$KILL_AFTER" -eq 1 ]; then
      if actana session kill "\${CORE_ARGS[@]+"\${CORE_ARGS[@]}"}" "\${LANE_SESSION[$index]}" >/dev/null 2>&1; then
        LANE_NOTE[$index]="$local_path (Session killed)"
      else
        LANE_NOTE[$index]="$local_path (saved; the Session would not stop — kill it by hand)"
      fi
    fi
  done

  [ "$pending" -gt 0 ] && sleep "$INTERVAL"
done

failures=0
for index in "\${!LANE_SESSION[@]}"; do
  printf '%s\\t%s\\t%s\\n' "\${LANE_SESSION[$index]}" "\${LANE_STATE[$index]}" "\${LANE_NOTE[$index]}"
  [ "\${LANE_STATE[$index]}" = "saved" ] || failures=$((failures + 1))
done

# A lane that produced nothing is a fact to report, not a gap to fill in.
exit $([ "$failures" -eq 0 ] && echo 0 || echo 1)
`,
};
