import { useEffect, useRef, type CSSProperties } from "react";
import type { LucideIcon } from "lucide-react";
import {
  File,
  FileCode,
  FilePen,
  FileSearch,
  FileText,
  FileStack,
  Folder,
  FolderOpen,
  FolderTree,
  FolderCode,
  Code,
  Code2,
  CodeXml,
  Terminal,
  SquareTerminal,
  GitBranch,
  GitCommitHorizontal,
  GitMerge,
  GitPullRequest,
  GitPullRequestArrow,
  GitFork,
  Search,
  SearchCode,
  SearchCheck,
  ScanText,
  Telescope,
  Microscope,
  LayoutDashboard,
  LayoutGrid,
  Palette,
  Paintbrush,
  PenTool,
  Type,
  Image,
  Frame,
  MousePointer,
  List,
  ListChecks,
  ListTodo,
  SquareCheck,
  Hammer,
  Wrench,
  Package,
  Container,
  Ship,
  Rocket,
  Send,
  Workflow,
  TestTube,
  FlaskConical,
  Bug,
  BugPlay,
  Cloud,
  CloudUpload,
  Server,
  Database,
  Table,
  Columns3,
  Box,
  Boxes,
  Globe,
  Network,
  Satellite,
  PlugZap,
  Webhook,
  Link,
  Share2,
  Shield,
  ShieldCheck,
  ShieldAlert,
  Lock,
  LockKeyhole,
  Key,
  Gauge,
  Activity,
  BarChart3,
  LineChart,
  PieChart,
  TrendingUp,
  Sparkles,
  WandSparkles,
  Zap,
  Brain,
  Bot,
  Cpu,
  TriangleAlert,
  AlertCircle,
  OctagonAlert,
  Trash,
  Trash2,
  Eraser,
  Ban,
  Clock,
  Calendar,
  CalendarClock,
  Hourglass,
  Timer,
  MessageSquare,
  Mail,
  Bell,
  Megaphone,
  Info,
  ArrowRightLeft,
  Replace,
  Shuffle,
  RefreshCw,
  History,
  Save,
  Archive,
  Book,
  BookOpen,
  NotebookPen,
  StickyNote,
  Pencil,
  SquarePen,
  Settings,
  Settings2,
  Sliders,
  Command,
  Play,
  Plus,
  Check,
  Upload,
  Download,
  Copy,
  ClipboardCheck,
  Eye,
} from "lucide-react";
import { DEFAULT_SESSION_ICON } from "~/lib/session-icons";

/**
 * Map of session-icon ids → lucide-react components. Kept in sync with the
 * SESSION_ICON_OPTIONS list in `~/lib/session-icons`; the title-generator
 * picks from those ids and the resulting string is used here at render time.
 */
const ICON_MAP: Record<string, LucideIcon> = {
  file: File,
  "file-code": FileCode,
  "file-pen": FilePen,
  "file-search": FileSearch,
  "file-text": FileText,
  "file-stack": FileStack,
  folder: Folder,
  "folder-open": FolderOpen,
  "folder-tree": FolderTree,
  "folder-code": FolderCode,
  code: Code,
  "code-2": Code2,
  "code-xml": CodeXml,
  terminal: Terminal,
  "square-terminal": SquareTerminal,
  "git-branch": GitBranch,
  "git-commit-horizontal": GitCommitHorizontal,
  "git-merge": GitMerge,
  "git-pull-request": GitPullRequest,
  "git-pull-request-arrow": GitPullRequestArrow,
  "git-fork": GitFork,
  search: Search,
  "search-code": SearchCode,
  "search-check": SearchCheck,
  "scan-text": ScanText,
  telescope: Telescope,
  microscope: Microscope,
  "layout-dashboard": LayoutDashboard,
  "layout-grid": LayoutGrid,
  palette: Palette,
  paintbrush: Paintbrush,
  "pen-tool": PenTool,
  type: Type,
  image: Image,
  frame: Frame,
  "mouse-pointer": MousePointer,
  list: List,
  "list-checks": ListChecks,
  "list-todo": ListTodo,
  "square-check": SquareCheck,
  hammer: Hammer,
  wrench: Wrench,
  package: Package,
  container: Container,
  ship: Ship,
  rocket: Rocket,
  send: Send,
  workflow: Workflow,
  "test-tube": TestTube,
  "flask-conical": FlaskConical,
  bug: Bug,
  "bug-play": BugPlay,
  cloud: Cloud,
  "cloud-upload": CloudUpload,
  server: Server,
  database: Database,
  table: Table,
  "columns-3": Columns3,
  box: Box,
  boxes: Boxes,
  globe: Globe,
  network: Network,
  satellite: Satellite,
  "plug-zap": PlugZap,
  webhook: Webhook,
  link: Link,
  "share-2": Share2,
  shield: Shield,
  "shield-check": ShieldCheck,
  "shield-alert": ShieldAlert,
  lock: Lock,
  "lock-keyhole": LockKeyhole,
  key: Key,
  gauge: Gauge,
  activity: Activity,
  "bar-chart-3": BarChart3,
  "line-chart": LineChart,
  "pie-chart": PieChart,
  "trending-up": TrendingUp,
  sparkles: Sparkles,
  "wand-sparkles": WandSparkles,
  zap: Zap,
  brain: Brain,
  bot: Bot,
  cpu: Cpu,
  "triangle-alert": TriangleAlert,
  "alert-circle": AlertCircle,
  "octagon-alert": OctagonAlert,
  trash: Trash,
  "trash-2": Trash2,
  eraser: Eraser,
  ban: Ban,
  clock: Clock,
  calendar: Calendar,
  "calendar-clock": CalendarClock,
  hourglass: Hourglass,
  timer: Timer,
  "message-square": MessageSquare,
  mail: Mail,
  bell: Bell,
  megaphone: Megaphone,
  info: Info,
  "arrow-right-left": ArrowRightLeft,
  replace: Replace,
  shuffle: Shuffle,
  "refresh-cw": RefreshCw,
  history: History,
  save: Save,
  archive: Archive,
  book: Book,
  "book-open": BookOpen,
  "notebook-pen": NotebookPen,
  "sticky-note": StickyNote,
  pencil: Pencil,
  "square-pen": SquarePen,
  settings: Settings,
  "settings-2": Settings2,
  sliders: Sliders,
  command: Command,
  play: Play,
  plus: Plus,
  check: Check,
  upload: Upload,
  download: Download,
  copy: Copy,
  "clipboard-check": ClipboardCheck,
  eye: Eye,
};

export function SessionIcon({
  name,
  size = 18,
  color,
  strokeWidth = 1.6,
  style,
  title,
  animate = false,
}: {
  name: string | null | undefined;
  size?: number;
  color?: string;
  strokeWidth?: number;
  style?: CSSProperties;
  title?: string;
  /**
   * When true, the glyph plays a continuous stroke-drawing loop (see the
   * `.mc-session-icon-drawing` rules in styles.css). Lucide glyphs vary wildly
   * in path length, so we normalize each sub-shape to `pathLength="1"` — that
   * lets one CSS keyframe (dashoffset 1 → 0 → -1) draw *any* icon in lockstep.
   */
  animate?: boolean;
}) {
  const Cmp = (name && ICON_MAP[name]) || ICON_MAP[DEFAULT_SESSION_ICON];
  const ref = useRef<SVGSVGElement>(null);

  useEffect(() => {
    const svg = ref.current;
    if (!svg || !animate) return;
    // Normalize every drawable child so stroke-dasharray:1 spans the whole
    // shape no matter its real geometry. Re-run when the glyph changes.
    for (const el of svg.querySelectorAll(":scope > *")) {
      el.setAttribute("pathLength", "1");
    }
  }, [animate, name]);

  return (
    <Cmp
      ref={ref}
      size={size}
      color={color}
      strokeWidth={strokeWidth}
      style={style}
      className={animate ? "mc-session-icon-drawing" : undefined}
      aria-hidden={title ? undefined : true}
    >
      {title ? <title>{title}</title> : null}
    </Cmp>
  );
}
